env = Environment( CXX = "g++-4.8" )

env.Append( CPPPATH = [ "/usr/local/include", "include/", "../AMQP-CPP/example/2", "../AMQP-CPP" ] )
env.Append( CCFLAGS = [ "-Wall", "-pedantic", "-g", "-O0", "-gdwarf-2", "-std=c++11" ] )
env.Append( LIBPATH = [ "../AMQP-CPP/example/2/", ".", "../AMQP-CPP" ] )
#env.Append( LIBS = [ "RabbitClient" ] )
env.Append( LIBS = [  "RabbitClientL2", "amqpcpp" ] )
env.Append( LINKFLAGS = [ "-pthread", "-std=c++11" ] )

sources = Split ("""
    ConnectionDetails.cpp
    simpleClient.cpp
    simpleConsumer.cpp
    simplePublisher.cpp
    clientImpl.cpp
    RabbitMessage.cpp
    """)

appSources = sources + [ "tester.cpp" ]
env.StaticLibrary( "RabbitClient", sources )

env.Program( "RabbitTest", appSources )
