env = Environment( CXX = "g++-4.8" )

env.Append( CPPPATH = [ "/usr/local/include", "include/", "../AMQP-CPP/example/2", "../../" ] )
env.Append( CCFLAGS = [ "-Wall", "-pedantic", "-g", "-O0", "-std=c++11", "-gdwarf-2" ] )
env.Append( LIBPATH = [ ".", "../.." ] )
#librt.so is for clock_gettime, in the test program
env.Append ( LIBS = [ "amqpcpp", "rt" ] )
env.Append( LINKFLAGS = [ "-pthread", "-std=c++11" ] )

sources = Split ("""
    AMQPClient.cpp
    AMQPConnectionHandler.cpp
    SmartBuffer.cpp
    AMQPEventLoop.cpp
    RabbitOperation.cpp
    Heartbeat.cpp
    RabbitJobManager.cpp
    """)

appSourced = sources + [ "main.cpp" ]
env.StaticLibrary( "RabbitClientL2", sources )
env.Program( "tester", appSourced )
